name: Generate Streak Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Streak Stats
        uses: muhammad-fiaz/github-readme-streak-stats@v1.0.1
        with:
          USERNAME: psamuelvijay
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THEME: dark
          OUTPUT_PATH: dist/github-streak.svg
          RING: "FF6B35"
          FIRE: "F7931E"
          STROKE: "FF6B35"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
